### ISSUE TITLE
Create convenience script for updating uStreamer settings

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/ansible-role-tinypilot#110]
It's currently fairly tedious to change uStreamer settings and apply them. You can edit the `ustreamer.service` file directly, but any changes will get overwritten by the next update. The current way to persist settings is:

1. Set values in `ustreamer.service`
1. `systemctl daemon-reload && sudo service ustreamer restart`
1. Set the same variables in `/home/tinypilot/settings.yml` so that they'll persist through the next update

We should add a convenience script that reads settings from `/home/tinypilot/settings.yml` (similar to [how `quick-install` does it](https://github.com/mtlynch/tinypilot/blob/5427fccb0fe6fe66460f5b243b485c22c9d29aed/quick-install#L57L67)) and then run a playbook with only `ansible-role-ustreamer`.

The playbook should:

* Skip fact gathering to save time (`gather_facts: no`)
* Run only tags related to ustreamer's systemd settings
  * We'll have to edit ansible-role-ustreamer to add those tags

The script should support a quiet mode so that we can call it programmatically from the frontend later.

---

Update: 2021-03-24

The desired flow for this script should be:

1. User updates `/home/tinypilot/settings.yml` with their desired uStreamer settings
1. User runs `/opt/tinypilot-privileged/update-video-settings`
1. `update-video-settings` (via Ansible) updates uStreamer's systemd file, reloads it, and restarts the uStreamer service

The script should only support changes to uStreamer role variables that affect uStreamer's runtime flags [in the systemd file](https://github.com/mtlynch/ansible-role-ustreamer/blob/57c424b9ba521393eb97e281f68bd46637c1f284/templates/ustreamer.systemd.j2). We shouldn't try to support every possible uStreamer role variable.

Also, we want to execute the uStreamer role, not the TinyPilot role. We really just want to execute the systemd play and then the two handlers come after it to reload and restart ustreamer. I'm hoping we can get this script to complete in <3 seconds.

I'm thinking the call to Ansible can be something like this:

```bash
readonly TINYPILOT_ROLE_NAME="mtlynch.ustreamer"
echo "- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - role: ${TINYPILOT_ROLE_NAME}" > update-settings.yml

ansible-playbook \
  update-settings.yml \
  --inventory localhost, \
  --extra-vars "@/home/tinypilot/settings.yml" \
  --extra-vars "@/home/ustreamer/config.yml" \
  --tags "config"
```

## Recovering settings from install

We have to work around [this hackery](https://github.com/mtlynch/tinypilot/blob/5ad43ceea18ab26ef4ce4889b3414426677e3cd3/quick-install#L29L47) because it means we lose a clean record of how uStreamer was provisioned. I think we can work around that by updating `quick-install` so that instead of setting those to transient environment variables, it appends the appropriate role variables in `/home/tinypilot/settings.yml`.

**Comment by jdeanwallace** [comment]
@mtlynch I've started my investigation into this task and it looks like we're forced to gather facts because [ansible-role-ustreamer relies on the `ansible_architecture` fact](https://github.com/mtlynch/ansible-role-ustreamer/blob/8d8fe7c62dcad764bb304492de47524488ba80fa/tasks/main.yml#L44). So if we don't gather facts then that ansible variable is undefined during runtime & fails.

Based on that, I'm just going to use the `install.yml` playbook (already created by the [`quick-install` script](https://github.com/mtlynch/tinypilot/blob/5427fccb0fe6fe66460f5b243b485c22c9d29aed/quick-install#L57L67)) while specifying the ustreamer ansible tag.

**Comment by mtlynch** [comment]
>it looks like we're forced to gather facts because ansible-role-ustreamer relies on the ansible_architecture fact. So if we don't gather facts then that ansible variable is undefined during runtime & fails.

We can avoid this by adding a tag to [this play](https://github.com/mtlynch/ansible-role-ustreamer/blob/8d8fe7c62dcad764bb304492de47524488ba80fa/tasks/main.yml#L134) (i.e., making a change to the ansible-role-ustreamer repo) and then running the role on our side with that tag specified.
