### ISSUE TITLE
create TinyPilot virtualenv fails

### ISSUE THREAD

**Issue by keithnet** [mtlynch/ansible-role-tinypilot#28]
The last tasks seems to fail:
TASK [mtlynch.tinypilot : create TinyPilot virtualenv] *************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/opt/tinypilot/venv/bin/pip3 list --format=freeze", "msg": "[Errno 2] No such file or directory: b'/opt/tinypilot/venv/bin/pip3': b'/opt/tinypilot/venv/bin/pip3'", "rc": 2}

Full output:
root@raspberrypi:/home/pi# curl -sS https://raw.githubusercontent.com/mtlynch/tinypilot/master/quick-install   | bash -
+ set -e
+ set -u
+ '[' -f /etc/nginx/sites-enabled/KVMPi.conf ']'
++ mktemp -d
+ pushd /tmp/tmp.yQ9opggT79
/tmp/tmp.yQ9opggT79 /home/pi
+ sudo apt-get install -y libssl-dev python3-dev python3-venv
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.7.3-1).
python3-venv is already the newest version (3.7.3-1).
libssl-dev is already the newest version (1.1.1d-0+deb10u3+rpt1).
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ python3 -m venv venv
+ . venv/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/tmp/tmp.yQ9opggT79/venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/tmp/tmp.yQ9opggT79/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' 'x(venv) ' '!=' x ']'
++ PS1='(venv) '
++ export PS1
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ pip install wheel==0.34.2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting wheel==0.34.2
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.34.2
+ pip install ansible==2.9.10
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ansible==2.9.10
Collecting cryptography (from ansible==2.9.10)
  Using cached https://www.piwheels.org/simple/cryptography/cryptography-3.0-cp37-cp37m-linux_armv7l.whl
Collecting PyYAML (from ansible==2.9.10)
  Using cached https://www.piwheels.org/simple/pyyaml/PyYAML-5.3.1-cp37-cp37m-linux_armv7l.whl
Collecting jinja2 (from ansible==2.9.10)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->ansible==2.9.10)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->ansible==2.9.10)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.14.1-cp37-cp37m-linux_armv7l.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible==2.9.10)
  Using cached https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp37-cp37m-linux_armv7l.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->ansible==2.9.10)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: six, pycparser, cffi, cryptography, PyYAML, MarkupSafe, jinja2, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.9.10 cffi-1.14.1 cryptography-3.0 jinja2-2.11.2 pycparser-2.20 six-1.15.0
+ echo '[defaults]
roles_path = /tmp/tmp.yQ9opggT79
interpreter_python = /usr/bin/python3
'
+ ansible-galaxy install mtlynch.tinypilot
- downloading role 'tinypilot', owned by mtlynch
- downloading role from https://github.com/mtlynch/ansible-role-tinypilot/archive/master.tar.gz
- extracting mtlynch.tinypilot to /tmp/tmp.yQ9opggT79/mtlynch.tinypilot
- mtlynch.tinypilot (master) was installed successfully
- adding dependency: mtlynch.ustreamer
- adding dependency: geerlingguy.nginx
- downloading role 'ustreamer', owned by mtlynch
- downloading role from https://github.com/mtlynch/ansible-role-ustreamer/archive/master.tar.gz
- extracting mtlynch.ustreamer to /tmp/tmp.yQ9opggT79/mtlynch.ustreamer
- mtlynch.ustreamer (master) was installed successfully
- downloading role 'nginx', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/2.8.0.tar.gz
- extracting geerlingguy.nginx to /tmp/tmp.yQ9opggT79/geerlingguy.nginx
- geerlingguy.nginx (2.8.0) was installed successfully
+ echo '- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  roles:
    - role: mtlynch.tinypilot'
+ ansible-playbook -i localhost, install.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [mtlynch.ustreamer : collect universal required apt packages] *************
ok: [localhost]

TASK [mtlynch.ustreamer : collect Raspberry Pi OS specific required apt packages] ***
ok: [localhost]

TASK [mtlynch.ustreamer : collect Debian-specific required apt packages] *******
skipping: [localhost]

TASK [mtlynch.ustreamer : collect Ubuntu-specific required apt packages] *******
skipping: [localhost]

TASK [mtlynch.ustreamer : install uStreamer pre-requisite packages] ************
ok: [localhost]

TASK [mtlynch.ustreamer : create ustreamer group] ******************************
ok: [localhost]

TASK [mtlynch.ustreamer : create ustreamer user] *******************************
ok: [localhost]

TASK [mtlynch.ustreamer : create uStreamer folder] *****************************
ok: [localhost]

TASK [mtlynch.ustreamer : get uStreamer repo] **********************************
ok: [localhost]

TASK [mtlynch.ustreamer : clean repository if needed] **************************
skipping: [localhost]

TASK [mtlynch.ustreamer : enable OpenMax IL acceleration on Pi OS] *************
ok: [localhost]

TASK [mtlynch.ustreamer : build uStreamer] *************************************
ok: [localhost]

TASK [mtlynch.ustreamer : fix uStreamer folder permissions] ********************
ok: [localhost]

TASK [mtlynch.ustreamer : install uStreamer as a service] **********************
ok: [localhost]

TASK [mtlynch.ustreamer : enable systemd uStreamer service file] ***************
ok: [localhost]

TASK [geerlingguy.nginx : Include OS-specific variables.] **********************
ok: [localhost]

TASK [geerlingguy.nginx : Define nginx_user.] **********************************
ok: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
included: /tmp/tmp.yQ9opggT79/geerlingguy.nginx/tasks/setup-Debian.yml for localhost

TASK [geerlingguy.nginx : Update apt cache.] ***********************************
ok: [localhost]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
ok: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [localhost]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [localhost]

TASK [geerlingguy.nginx : Remove default nginx vhost config file (if configured).] ***
ok: [localhost]

TASK [geerlingguy.nginx : Ensure nginx_vhost_path exists.] *********************
ok: [localhost]

TASK [geerlingguy.nginx : Add managed vhost config files.] *********************
ok: [localhost] => (item={'listen': '80 default_server', 'server_name': 'tinypilot', 'root': '/opt/tinypilot', 'index': 'index.html', 'extra_parameters': 'proxy_buffers 16 16k;\nproxy_buffer_size 16k;\nproxy_set_header Host $host;\nproxy_set_header X-Forwarded-For $remote_addr;\nproxy_http_version 1.1;\n\nlocation /socket.io {\n  proxy_pass http://tinypilot;\n  proxy_set_header Upgrade $http_upgrade;\n  proxy_set_header Connection "Upgrade";\n}\nlocation /state {\n  proxy_pass http://ustreamer;\n}\nlocation /stream {\n  proxy_pass http://ustreamer;\n}\nlocation / {\n  proxy_pass http://tinypilot;\n}\nlocation ~* ^/.+\\.(html|js|js.map|css|jpeg|png|ico)$ {\n  root "/opt/tinypilot/app/static";\n}\n'})

TASK [geerlingguy.nginx : Remove managed vhost config files.] ******************
skipping: [localhost] => (item={'listen': '80 default_server', 'server_name': 'tinypilot', 'root': '/opt/tinypilot', 'index': 'index.html', 'extra_parameters': 'proxy_buffers 16 16k;\nproxy_buffer_size 16k;\nproxy_set_header Host $host;\nproxy_set_header X-Forwarded-For $remote_addr;\nproxy_http_version 1.1;\n\nlocation /socket.io {\n  proxy_pass http://tinypilot;\n  proxy_set_header Upgrade $http_upgrade;\n  proxy_set_header Connection "Upgrade";\n}\nlocation /state {\n  proxy_pass http://ustreamer;\n}\nlocation /stream {\n  proxy_pass http://ustreamer;\n}\nlocation / {\n  proxy_pass http://tinypilot;\n}\nlocation ~* ^/.+\\.(html|js|js.map|css|jpeg|png|ico)$ {\n  root "/opt/tinypilot/app/static";\n}\n'})

TASK [geerlingguy.nginx : Remove legacy vhosts.conf file.] *********************
ok: [localhost]

TASK [geerlingguy.nginx : Copy nginx configuration in place.] ******************
ok: [localhost]

TASK [geerlingguy.nginx : Ensure nginx service is running as configured.] ******
ok: [localhost]

TASK [mtlynch.tinypilot : enable dwc2 driver in boot config] *******************
ok: [localhost]

TASK [mtlynch.tinypilot : enable dwc2 driver in modules] ***********************
ok: [localhost]

TASK [mtlynch.tinypilot : copy HID initializer script] *************************
ok: [localhost]

TASK [mtlynch.tinypilot : install HID initializer as a service] ****************
ok: [localhost]

TASK [mtlynch.tinypilot : enable systemd HID initializer service file] *********
ok: [localhost]

TASK [mtlynch.tinypilot : install TinyPilot pre-requisite packages] ************
ok: [localhost]

TASK [mtlynch.tinypilot : create tinypilot group] ******************************
ok: [localhost]

TASK [mtlynch.tinypilot : create tinypilot user] *******************************
ok: [localhost]

TASK [mtlynch.tinypilot : enable passwordless sudo for shutdown command] *******
ok: [localhost]

TASK [mtlynch.tinypilot : create TinyPilot folder] *****************************
ok: [localhost]

TASK [mtlynch.tinypilot : get TinyPilot repo] **********************************
ok: [localhost]

TASK [mtlynch.tinypilot : create TinyPilot virtualenv] *************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/opt/tinypilot/venv/bin/pip3 list --format=freeze", "msg": "[Errno 2] No such file or directory: b'/opt/tinypilot/venv/bin/pip3': b'/opt/tinypilot/venv/bin/pip3'", "rc": 2}

PLAY RECAP *********************************************************************
localhost                  : ok=35   changed=0    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0

**Comment by mtlynch** [comment]
This looks similar to https://github.com/mtlynch/tinypilot/issues/85

Could you try upgrading your packages?

```bash
sudo apt-get update && \
  sudo apt-get upgrade -y
```

**Comment by keithnet** [comment]
Sorry for opening another issue. 

My packages were up-to-date, but I tried again:

pi@raspberrypi:~ $ sudo apt-get update && \
>   sudo apt-get upgrade -y
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


Re-ran quick-install. same error.

This is a brand new raspberry pie set up following all of your instructions just for this purpose.

Thx.

**Comment by mtlynch** [comment]
Thanks, @keithnet. Hmm, I'm trying to figure out why certain Pis run into this. Could you paste the output of this command?

```bash
ls -l /opt/tinypilot /opt/tinypilot/venv/ /opt/tinypilot/venv/bin/ && \
  cat /etc/os-release
```

**Comment by keithnet** [comment]
root@raspberrypi:/home/pi# ls -l /opt/tinypilot /opt/tinypilot/venv/ /opt/tinypilot/venv/bin/ && \
>   cat /etc/os-release
/opt/tinypilot:
total 2700
drwxr-xr-x 4 root root    4096 Aug  9 20:51 app
-rw-r--r-- 1 root root      55 Aug  2 16:35 COPYRIGHT
-rw-r--r-- 1 root root 2704070 Aug  2 16:35 demo.gif
-rw-r--r-- 1 root root      71 Aug  2 16:35 dev_requirements.txt
-rwxr-xr-x 1 root root     925 Aug  2 16:35 enable-usb-hid
drwxr-xr-x 2 root root    4096 Aug  2 16:35 hooks
-rw-r--r-- 1 root root       0 Aug  2 16:35 __init__.py
-rw-r--r-- 1 root root    1053 Aug  2 16:35 LICENSE
-rw-r--r-- 1 root root      65 Aug  2 16:35 MANIFEST.in
-rwxr-xr-x 1 root root     856 Aug  9 20:51 quick-install
-rw-r--r-- 1 root root    5470 Aug  9 20:51 README.md
-rw-r--r-- 1 root root      70 Aug  2 16:35 requirements.txt
-rwxr-xr-x 1 root root     877 Aug  2 16:35 run_build
-rw-r--r-- 1 root root     465 Aug  2 16:35 setup.py
drwxr-xr-x 6 root root    4096 Aug  2 16:35 venv

/opt/tinypilot/venv/:
total 20
drwxr-xr-x 2 root root 4096 Aug  2 16:36 bin
drwxr-xr-x 3 root root 4096 Aug  2 16:36 include
drwxr-xr-x 3 root root 4096 Aug  2 16:35 lib
-rw-r--r-- 1 root root   89 Aug  2 16:35 pyvenv.cfg
drwxr-xr-x 3 root root 4096 Aug  2 16:35 share

/opt/tinypilot/venv/bin/:
total 36
-rw-r--r-- 1 root root 2195 Aug  2 16:35 activate
-rw-r--r-- 1 root root 1251 Aug  2 16:35 activate.csh
-rw-r--r-- 1 root root 2403 Aug  2 16:35 activate.fish
-rwxr-xr-x 1 root root  248 Aug  2 16:35 easy_install
-rwxr-xr-x 1 root root  248 Aug  2 16:35 easy_install-3.7
-rwxr-xr-x 1 root root  226 Aug  2 16:36 flask
-rwxr-xr-x 1 root root  230 Aug  2 16:35 pip
-rwxr-xr-x 1 root root  230 Aug  2 16:35 pip3
-rwxr-xr-x 1 root root  230 Aug  2 16:35 pip3.7
lrwxrwxrwx 1 root root    7 Aug  2 16:35 python -> python3
lrwxrwxrwx 1 root root   36 Aug  2 16:35 python3 -> /tmp/tmp.Zg85Jt4Fyr/venv/bin/python3
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by mtlynch** [comment]
That's strange because everything looks right. The file it's complaining about seems to be there:

>fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/opt/tinypilot/venv/bin/pip3 list --format=freeze", "msg": "[Errno 2] No such file or directory: b'/opt/tinypilot/venv/bin/pip3': b'/opt/tinypilot/venv/bin/pip3'", "rc": 2}

...

>root@raspberrypi:/home/pi# ls -l /opt/tinypilot /opt/tinypilot/venv/ /opt/tinypilot/venv/bin/ && \
...
/opt/tinypilot/venv/bin/:
total 36
-rwxr-xr-x 1 root root 230 Aug 2 16:35 pip3

I'll try to repro on my side and follow up.

**Comment by mtlynch** [comment]
I tried doing the exact same setup, and I'm not able to repro the failure. It installs successfully on my end, and I can't figure out what's different:

https://gist.github.com/mtlynch/653a0b287be1c29b03949cb95f494303

I'm going to keep investigating and see if I can find anything.

My only thought is maybe the fact that you're running as `root`? Can you try running the original quick-install command as the `pi` user?

**Comment by keithnet** [comment]
Just tried it as pi and not root and same result.

**Comment by mtlynch** [comment]
Okay, two other ideas.

1. Can you try manually creating the virtualenv?

```bash
pushd /opt/tinypilot
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
deactivate
popd
```

2. Can you try installing with this verbose version of the installer so we can try to get more hints?

```bash
curl -sS https://raw.githubusercontent.com/mtlynch/tinypilot/install-verbose/quick-install | bash -
```

**Comment by keithnet** [comment]
I tried the verbose version first. Here's the part where it died:

TASK [mtlynch.tinypilot : create TinyPilot virtualenv] *************************
task path: /tmp/tmp.eZHTuUvE7U/mtlynch.tinypilot/tasks/main.yml:50
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pi
<localhost> EXEC /bin/sh -c 'echo ~pi && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/pi/.ansible/tmp `"&& mkdir /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019 && echo ansible-tmp-1597024575.7156525-6920-46199644149019="` echo /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019 `" ) && sleep 0'
Using module file /tmp/tmp.eZHTuUvE7U/venv/lib/python3.7/site-packages/ansible/modules/packaging/language/pip.py
<localhost> PUT /home/pi/.ansible/tmp/ansible-local-566419teqpwn/tmp3uk6_p1r TO /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019/AnsiballZ_pip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019/ /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019/AnsiballZ_pip.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-aglmhmkplstlhnrpflatbrihkhfnkozb ; /usr/bin/python3 /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019/AnsiballZ_pip.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/pi/.ansible/tmp/ansible-tmp-1597024575.7156525-6920-46199644149019/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_pip_payload_o7jd6cyq/ansible_pip_payload.zip/ansible/module_utils/basic.py", line 2588, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "/opt/tinypilot/venv/bin/pip3 list --format=freeze",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": null,
            "requirements": "/opt/tinypilot/requirements.txt",
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": "/opt/tinypilot/venv",
            "virtualenv_command": "python3 -m venv venv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "msg": "[Errno 2] No such file or directory: b'/opt/tinypilot/venv/bin/pip3': b'/opt/tinypilot/venv/bin/pip3'",
    "rc": 2
}

PLAY RECAP *********************************************************************
localhost                  : ok=35   changed=0    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0

I'm going to hold off on manually creating the virtualenv until you tell me try that instead.

**Comment by mtlynch** [comment]
Yeah, it unfortunately doesn't give us much. Can you try the manual venv command?

**Comment by keithnet** [comment]
pi@raspberrypi:~ $ pushd /opt/tinypilot
/opt/tinypilot ~
pi@raspberrypi:/opt/tinypilot $ python3 -m venv venv
Error: [Errno 13] Permission denied: '/opt/tinypilot/venv/pyvenv.cfg'
pi@raspberrypi:/opt/tinypilot $ . venv/bin/activate
(venv) pi@raspberrypi:/opt/tinypilot $ pip install -r requirements.txt
-bash: /opt/tinypilot/venv/bin/pip: /opt/tinypilot/venv/bin/python3: bad interpreter: No such file or directory
(venv) pi@raspberrypi:/opt/tinypilot $ deactivate
pi@raspberrypi:/opt/tinypilot $ popd
~

This help?

pi@raspberrypi:~ $ ls -l /opt/tinypilot/venv/bin/python3
lrwxrwxrwx 1 root root 36 Aug  2 16:35 /opt/tinypilot/venv/bin/python3 -> /tmp/tmp.Zg85Jt4Fyr/venv/bin/python3
pi@raspberrypi:~ $ ls -l /opt/tinypilot/venv/bin/python3
lrwxrwxrwx 1 root root 36 Aug  2 16:35 /opt/tinypilot/venv/bin/python3 -> /tmp/tmp.Zg85Jt4Fyr/venv/bin/python3
pi@raspberrypi:~ $ ls -l /opt/tinypilot/venv/bin/pip
-rwxr-xr-x 1 root root 230 Aug  2 16:35 /opt/tinypilot/venv/bin/pip
pi@raspberrypi:~ $ ls -l /tmp/tmp.Zg85Jt4Fyr/venv/bin/python3
ls: cannot access '/tmp/tmp.Zg85Jt4Fyr/venv/bin/python3': No such file or directory

**Comment by mtlynch** [comment]
>This help?

Yes! Now I see what's going on. In the `/opt/tinypilot` virtualenv, `/opt/tinypilot/venv/bin/python3` should point to the system-wide python3 binary at `/usr/bin/python3`, but it's pointing to the virtualenv copy in the temporary install directory. I think it's saying no such file because it doesn't have permissions to access the one in the install directory.

Let me think about how to fix this correctly. In the meantime, I think this should do as a workaround:

```bash
sudo rm -rf /opt/tinypilot/venv && \
  sudo chown $(whoami) /opt/tinypilot -R && \
  pushd /opt/tinypilot && \
  python3 -m venv venv && \
  . venv/bin/activate && \
  pip install -r requirements.txt && \
  deactivate && \
  popd
```

And then re-run the normal installer.

**Comment by keithnet** [comment]
Done. Normal installer worked without error.

I do get 502 Bad Gateway | nginx/1.14.2 when I visit the web server on my pi tho.

**Comment by keithnet** [comment]
> I do get 502 Bad Gateway | nginx/1.14.2 when I visit the web server on my pi tho.

A reboot of the pi fixed it.

**Comment by mtlynch** [comment]
Thanks for your patience on this. I believe #32 fixes this.
