### ISSUE TITLE
python-pip not available on Ubuntu 20.10

### ISSUE THREAD

**Issue by LalitMaganti** [mtlynch/ansible-role-tinypilot#76]
On Ubuntu 20.10, I get the following error when running the this role:
```
TASK [mtlynch.tinypilot : install TinyPilot pre-requisite packages] ************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python-pip' is available"}
```

I believe this is because python-pip was removed from Ubuntu (and Debian) repos due to Python 2's deprecation. Should this be changed to python3-pip?

**Comment by mtlynch** [comment]
I [have a fix for this](https://github.com/mtlynch/ansible-role-tinypilot/pull/56) prepared a while back, but I ended up not merging it because I've never been able to get TinyPilot working on Ubuntu.

Are you able to get the USB gadget functionality working under Ubuntu?

**Comment by LalitMaganti** [comment]
My OTG adapter has not arrived so I cannot test this but at least the display part of TinyPilot seems to be working correctly for me.

**Comment by LalitMaganti** [comment]
Had a couple of realisations in sequence:
1. I don't need to wait for OTG adapter - I can connect the Pi directly to my desktop
2. Ubuntu doesn't mount the FAT32 boot partition at /boot but at /boot/firmware. This means that https://github.com/mtlynch/ansible-role-tinypilot/blob/master/tasks/install_usb_gadget.yml#L9 is not valid for Ubuntu and should be changed to /boot/firmware/config.txt

Once I changed /boot/firmware/config.txt manually, keyboard and mouse functionality started working on Tinypilot :)

**Comment by mtlynch** [comment]
>https://github.com/mtlynch/ansible-role-tinypilot/blob/master/tasks/install_usb_gadget.yml#L9 is not valid for Ubuntu and should be changed to /boot/firmware/config.txt

Ooooh, that was the piece I was always missing. Thanks!
